#!/usr/bin/env bash
# Regenerate src/sql/pagc_tables.sql.in from PG's vendored pagc_tables.sql.
#
# Why we maintain our own copy: the upstream `postgis/address_standardizer`
# C library (and the duckdb-address-standardizer community ext that wraps it)
# ships PAGC rule data with longer-form standardization targets — e.g.
# `SER RD → SERVICE ROAD`. PG's `postgis_tiger_geocoder` extension hand-
# modified that rule data to TIGER's vocabulary — `SER RD → SVC RD` and
# similar abbreviations, plus extra composite rules like `SERVICE DR → SVC DR`
# that upstream lacks. Since we're geocoding against TIGER, PG's TIGER-tuned
# rules give us better candidate-matching. So we ship them in our extension
# under `tiger.pagc_lex/gaz/rules` and have `from_pagc` call
# `standardize_address('tiger.pagc_lex', ...)` instead of the community
# extension's upstream-faithful `us_lex` etc.
#
# Output: src/sql/pagc_tables.sql.in — DDL + transformed INSERTs from PG's
# pagc_tables.sql, with @TIGER@ placeholder for catalog substitution and
# is_custom column dropped (DuckDB doesn't need PG's custom-vs-shipped
# distinction).
#
# Usage:
#   ./scripts/regenerate_pagc_tables.sh
#
# Prereq: the postgis_tiger_geocoder mirror cloned into
#   benchmark/pg/tiger_geocoder/  (per .gitignore note)

set -eu -o pipefail
cd "$(dirname "$0")/.."

PG_SRC=benchmark/pg/tiger_geocoder/src/pagc_normalize/pagc_tables.sql
OUT=src/sql/pagc_tables.sql.in

[[ -f "$PG_SRC" ]] || { echo "ERROR: $PG_SRC not found. Clone the mirror first." >&2; exit 2; }

# Header + DDL. Schema matches us_address_standardizer's tables (so we can
# pass `tiger.pagc_lex` etc. as the table-name argument to standardize_address
# and the C extension's row reader expects the same column shape).
cat > "$OUT" <<'HEADER'
-- TIGER-tuned PAGC rule data, ported from postgis_tiger_geocoder's
-- src/pagc_normalize/pagc_tables.sql.
--
-- These rules differ from the upstream postgis/address_standardizer rules
-- (which the duckdb-address-standardizer community ext ships under
-- us_lex/us_gaz/us_rules). PG's tiger_geocoder hand-modified upstream's
-- data to use TIGER's abbreviated forms (SVC RD instead of SERVICE ROAD,
-- composite rules like SERVICE DR → SVC DR, etc.).
--
-- Generated by scripts/regenerate_pagc_tables.sh from PG's pagc_tables.sql.
-- Do not hand-edit; regenerate.

CREATE TABLE IF NOT EXISTS @TIGER@.pagc_lex (
    id INTEGER PRIMARY KEY,
    seq INTEGER,

    stdword VARCHAR,
    token INTEGER
);
CREATE TABLE IF NOT EXISTS @TIGER@.pagc_gaz (
    id INTEGER PRIMARY KEY,
    seq INTEGER,
    word VARCHAR,
    stdword VARCHAR,
    token INTEGER
);
CREATE TABLE IF NOT EXISTS @TIGER@.pagc_rules (
    id INTEGER PRIMARY KEY,
    rule VARCHAR
);

-- Idempotent re-load: drop rows that came from a previous run before
-- inserting the current snapshot.
DELETE FROM @TIGER@.pagc_lex;
DELETE FROM @TIGER@.pagc_gaz;
DELETE FROM @TIGER@.pagc_rules;

HEADER

# Lex/gaz transformation: drop ', is_custom' from column list, drop the
# trailing ', false' or ', true' from VALUES, and qualify the table name.
# Rules transformation: just qualify the table name (no is_custom in INSERT).
awk '
  /^INSERT INTO pagc_(lex|gaz) \(id, seq, word, stdword, token, is_custom\) [Vv][Aa][Ll][Uu][Ee][Ss]/ {
    sub(/, is_custom/, "")
    sub(/pagc_lex/,  "@TIGER@.pagc_lex")
    sub(/pagc_gaz/,  "@TIGER@.pagc_gaz")
    sub(/, (false|true)\);$/, ");")
    sub(/[Vv][Aa][Ll][Uu][Ee][Ss]/, "VALUES")
    print
    next
  }
  /^INSERT INTO pagc_rules \(id, rule\) [Vv][Aa][Ll][Uu][Ee][Ss]/ {
    sub(/pagc_rules/, "@TIGER@.pagc_rules")
    sub(/[Vv][Aa][Ll][Uu][Ee][Ss]/, "VALUES")
    print
    next
  }
' "$PG_SRC" >> "$OUT"

n_lex=$(grep -c "INTO @TIGER@.pagc_lex"   "$OUT")
n_gaz=$(grep -c "INTO @TIGER@.pagc_gaz"   "$OUT")
n_rul=$(grep -c "INTO @TIGER@.pagc_rules" "$OUT")
sz=$(wc -c < "$OUT" | tr -d ' ')

echo "Wrote $OUT ($sz bytes):"
echo "  pagc_lex   inserts: $n_lex"
echo "  pagc_gaz   inserts: $n_gaz"
echo "  pagc_rules inserts: $n_rul"
